AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  FHIR validator lambda

Parameters:
  LogLevel:
    Type: String
    Description: The log level to set in the lambda
    Default: "INFO"
  LogRetentionDays:
    Type: Number
    Description: How long to keep logs for
    Default: 30
    AllowedValues:
      [
        1,
        3,
        5,
        7,
        14,
        30,
        60,
        90,
        120,
        150,
        180,
        365,
        400,
        545,
        731,
        1096,
        1827,
        2192,
        2557,
        2922,
        3288,
        3653,
      ]
  EnableAlerts:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false

Resources:
  FHIRValidatorUKCoreResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: lambda_resources.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        CloudWatchKMSKey: !ImportValue account-resources-cdk-uk:KMS:CloudwatchLogsKmsKey:Arn
        SplunkSubscriptionFilterRole: !ImportValue account-resources-cdk-uk:IAM:SplunkSubscriptionFilterRole:Arn
        SplunkDeliveryStream: !ImportValue laaccount-resources-cdk-uk:Firehose:SplunkDeliveryStream:Arn
        EnableSplunk: "true"
        LambdaName: !Sub "${AWS::StackName}-FHIRValidatorUKCore"
        LambdaArn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AWS::StackName}-FHIRValidatorUKCore
        LogRetentionDays: !Ref LogRetentionDays

  FHIRValidatorUKCore:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-FHIRValidatorUKCore"
      CodeUri: ../
      Handler: software.nhs.fhirvalidator.handler.HandlerStream::handleRequest
      Role: !GetAtt FHIRValidatorUKCoreResources.Outputs.LambdaRoleArn
      SnapStart:
        ApplyOn: PublishedVersions
      AutoPublishAlias: snap
      Timeout: 600
      MemorySize: 4096
      Architectures:
        - x86_64
      Runtime: java25
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:38"
      Environment:
        Variables:
          AWS_LAMBDA_LOG_LEVEL: !Ref LogLevel
          POWERTOOLS_LOG_LEVEL: !Ref LogLevel
          PROFILE_MANIFEST_FILE: uk_core.manifest.json
    Metadata:
      guard:
        SuppressedRules:
          - LAMBDA_DLQ_CHECK
          - LAMBDA_INSIDE_VPC
          - LAMBDA_CONCURRENCY_CHECK

  Alarms:
    Type: AWS::Serverless::Application
    Properties:
      Location: alarms/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        EnableAlerts: !Ref EnableAlerts
        FHIRValidatorUKCoreLambdaName: !Ref FHIRValidatorUKCore

Outputs:
  FHIRValidatorUKCoreLambdaName:
    Description: Name of the FHIR validator UK Core lambda
    Value: !Ref FHIRValidatorUKCore
    Export:
      Name:
        !Join [":", [!Ref "AWS::StackName", "FHIRValidatorUKCoreLambdaName"]]
  FHIRValidatorUKCoreLambdaArn:
    Description: Arn of the FHIR validator UK Core lambda
    Value: !GetAtt FHIRValidatorUKCore.Arn
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FHIRValidatorUKCoreLambdaArn"]]
