name: sam release code

on:
  workflow_call:
    inputs:
      STACK_NAME:
        required: true
        type: string
      ARTIFACT_BUCKET_PREFIX:
        required: true
        type: string
      TARGET_ENVIRONMENT:
        required: true
        type: string
      BUILD_ARTIFACT:
        required: true
        type: string
      VERSION_NUMBER:
        required: true
        type: string
      COMMIT_ID:
        required: true
        type: string
      LOG_LEVEL:
        required: true
        type: string
      LOG_RETENTION_DAYS:
        required: true
        type: string
      ENABLE_ALERTS:
        type: boolean
        default: true
      pinned_image:
        type: string
        required: true
    secrets:
      CLOUD_FORMATION_DEPLOY_ROLE:
        required: true
      DEV_CLOUD_FORMATION_CHECK_VERSION_ROLE:
        required: false
      INT_CLOUD_FORMATION_CHECK_VERSION_ROLE:
        required: false
      PROD_CLOUD_FORMATION_CHECK_VERSION_ROLE:
        required: false
      DEV_CLOUD_FORMATION_EXECUTE_LAMBDA_ROLE:
        required: false

permissions: {}

jobs:
  sam_release_code:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.TARGET_ENVIRONMENT }}
    container:
      image: ${{ inputs.pinned_image }}
      options: --user 1001:1001 --group-add 128
    defaults:
      run:
        shell: bash
    permissions:
      id-token: write
      contents: write

    steps:
      - name: copy .tool-versions
        run: |
          cp /home/vscode/.tool-versions "$HOME/.tool-versions"
      - name: Checkout local github actions
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
          fetch-depth: 0
          sparse-checkout: |
            .github

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.CLOUD_FORMATION_DEPLOY_ROLE }}
          role-session-name: fhir-validator-lambda-release-code

      - name: download build artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: ${{ inputs.BUILD_ARTIFACT }}
          path: .

      - name: release code
        shell: bash
        working-directory: .github/scripts
        env:
          ARTIFACT_BUCKET_PREFIX: fhir_validator/${{ inputs.ARTIFACT_BUCKET_PREFIX }}
          COMMIT_ID: ${{ inputs.COMMIT_ID }}
          LOG_LEVEL: ${{ inputs.LOG_LEVEL }}
          LOG_RETENTION_DAYS: ${{ inputs.LOG_RETENTION_DAYS }}
          STACK_NAME: ${{ inputs.STACK_NAME }}
          TARGET_ENVIRONMENT: ${{ inputs.TARGET_ENVIRONMENT }}
          TEMPLATE_FILE: template.yaml
          VERSION_NUMBER: ${{ inputs.VERSION_NUMBER }}
          ENABLE_ALERTS: ${{ inputs.ENABLE_ALERTS }}
        run: ./release_code.sh

      - name: Checkout gh-pages
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: true
          ref: gh-pages
          path: gh-pages

      - name: update release tag in github pages
        if: ${{ inputs.TARGET_ENVIRONMENT != 'dev-pr' }}
        run: |
          cd gh-pages
          NOW=$(date +'%Y-%m-%dT%H:%M:%S')
          echo "tag,release_datetime" > "_data/${TARGET_ENVIRONMENT}_latest.csv"
          echo "${VERSION_NUMBER},${NOW}" >> "_data/${TARGET_ENVIRONMENT}_latest.csv"
          echo "${VERSION_NUMBER},${NOW}" >> "_data/${TARGET_ENVIRONMENT}_deployments.csv"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add "_data/${TARGET_ENVIRONMENT}_latest.csv"
          git add "_data/${TARGET_ENVIRONMENT}_deployments.csv"
          git commit -m "update releases for ${TARGET_ENVIRONMENT}"
          parallel --retries 10 --delay 3 ::: "git pull --rebase && git push"
        env:
          VERSION_NUMBER: ${{ inputs.VERSION_NUMBER }}
          TARGET_ENVIRONMENT: ${{ inputs.TARGET_ENVIRONMENT }}
